name: Convert Markdown to PDF

on:
  push:
    paths:
      - 'curriculum_vitae.md'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Convert Markdown to PDF
        run: |
          pandoc curriculum_vitae.md -o src/curriculum_vitae.pdf --pdf-engine=xelatex \
            "-V" "geometry:margin=1in" \
            "-V" "pagestyle=empty"

      - name: Commit and push PDF
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/curriculum_vitae.pdf
          git commit -m "Update curriculum_vitae.pdf"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
